# Generated by Django 3.2.9 on 2021-11-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ORGANIZATIONS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Airport operator', 'Airport operator'), ('Airspace user', 'Airspace user'), ('Ground handler', 'Ground handler'), ('Network manager', 'Network manager'), ('Meteorological service provider', 'Meteorological service provider')], default='Airport operator', max_length=255, verbose_name='type')),
            ],
        ),
    ]
