# Generated by Django 3.2.9 on 2021-11-26 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0003_auto_20211126_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='PUBLISHER_POLICY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy_type', models.CharField(choices=[('TOPIC BASED', 'topic_based'), ('DATA STRUCTURE BASED', 'data_structure_based')], default='TOPIC BASED', max_length=255, verbose_name='policy_type')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='SUBSCRIBER_POLICY',
        ),
    ]
