# Generated by Django 3.2.9 on 2021-11-26 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0004_auto_20211126_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='DATA_CATALOGUE_ELEMENT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_path', models.CharField(max_length=500)),
                ('data_schema', models.CharField(max_length=500)),
                ('data_type', models.CharField(choices=[('TOPIC ELEMENT', 'topic_element'), ('DATA ELEMENT', 'data_element')], default='TOPIC ELEMENT', max_length=255, verbose_name='data_type')),
            ],
        ),
        migrations.CreateModel(
            name='SUBSCRIBER_POLICY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_end_point', models.CharField(max_length=255)),
                ('catalogue_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.data_catalogue_element')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.publisher_policy')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='publisher_policy',
            name='catalogue_element',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.data_catalogue_element'),
            preserve_default=False,
        ),
    ]
