# Generated by Django 3.2.9 on 2021-11-29 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0007_topic_policy_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='DATA_ELEMENT_POLICY_ITEM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('path', models.CharField(max_length=500)),
                ('publisher_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.publisher_policy')),
                ('subscriber_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.subscriber_policy')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
