# Generated by Django 3.2.9 on 2021-11-30 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20211129_1606'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='data_catalogue_element',
            table='DATA_CATALOGUE_ELEMENT',
        ),
        migrations.AlterModelTable(
            name='organizations',
            table='ORGANIZATIONS',
        ),
        migrations.AlterModelTable(
            name='publisher_policy',
            table='PUBLISHER_POLICY',
        ),
        migrations.AlterModelTable(
            name='subscriber_policy',
            table='SUBSCRIBER_POLICY',
        ),
        migrations.AlterModelTable(
            name='transformation_item',
            table='TRANSFORMATION_ITEM',
        ),
        migrations.AlterModelTable(
            name='user_info',
            table='USER_INFO',
        ),
    ]
