# Generated by Django 3.2.9 on 2021-11-30 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20211130_0803'),
    ]

    operations = [
        migrations.CreateModel(
            name='POLICY_ASSOCIATION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.publisher_policy')),
                ('subscriber_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.subscriber_policy')),
            ],
            options={
                'db_table': 'POLICY_ASSOCIATION',
            },
        ),
    ]
