# Generated by Django 3.2.9 on 2021-11-30 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_policy_association'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber_policy',
            name='policy',
        ),
    ]
