# Generated by Django 3.2.9 on 2021-12-01 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_remove_subscriber_policy_policy'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='organizations',
            table='ORGANIZATION',
        ),
    ]
