# Generated by Django 3.2.9 on 2021-12-03 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_user_info_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher_policy',
            name='catalogue_element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.data_catalogue_element'),
        ),
        migrations.AlterField(
            model_name='subscriber_policy',
            name='catalogue_element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.data_catalogue_element'),
        ),
    ]
