# Generated by Django 3.2.9 on 2021-12-07 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_alter_publisher_policy_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transformation_item',
            name='data_schema',
        ),
        migrations.RemoveField(
            model_name='transformation_item',
            name='organization',
        ),
    ]
