# Generated by Django 3.2.9 on 2021-12-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_auto_20211207_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformation_item',
            name='organization_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transformation_item',
            name='organization_type',
            field=models.CharField(choices=[('Airport operator', 'Airport operator'), ('Airspace user', 'Airspace user'), ('Ground handler', 'Ground handler'), ('Network manager', 'Network manager'), ('Meteorological service provider', 'Meteorological service provider')], max_length=255, null=True, verbose_name='type'),
        ),
    ]
