# Generated by Django 3.2.9 on 2021-12-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20211207_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_catalogue_element',
            name='data_type',
            field=models.CharField(choices=[('TOPIC ELEMENT', 'topic_element'), ('DATA ELEMENT', 'data_element')], max_length=255, null=True, verbose_name='data_type'),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='type',
            field=models.CharField(choices=[('Airport operator', 'Airport operator'), ('Airspace user', 'Airspace user'), ('Ground handler', 'Ground handler'), ('Network manager', 'Network manager'), ('Meteorological service provider', 'Meteorological service provider')], max_length=255, null=True, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='transformation_item',
            name='item_operator',
            field=models.CharField(choices=[('Endpoint restriction', 'endpoint_restriction'), ('Payload extraction', 'payload_extraction')], max_length=255, verbose_name='item_operator'),
        ),
        migrations.AlterField(
            model_name='transformation_item',
            name='item_type',
            field=models.CharField(choices=[('Organization type', 'organization_type'), ('Organization name', 'organization_name'), ('Data based', 'data_based')], max_length=255, verbose_name='item_type'),
        ),
    ]
