# Generated by Django 3.2.9 on 2021-12-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_auto_20211207_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber_policy',
            name='policy_type',
            field=models.CharField(choices=[('TOPIC BASED', 'topic_based'), ('DATA STRUCTURE BASED', 'data_structure_based')], default='TOPIC BASED', max_length=255, verbose_name='policy_type'),
        ),
    ]
