# Generated by Django 3.2.9 on 2021-12-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_subscriber_policy_policy_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher_policy',
            name='policy_type',
            field=models.CharField(choices=[('TOPIC BASED', 'topic_based'), ('DATA STRUCTURE BASED', 'data_structure_based')], max_length=255, verbose_name='policy_type'),
        ),
        migrations.AlterField(
            model_name='subscriber_policy',
            name='policy_type',
            field=models.CharField(choices=[('TOPIC BASED', 'topic_based'), ('DATA STRUCTURE BASED', 'data_structure_based')], max_length=255, verbose_name='policy_type'),
        ),
    ]
