# Generated by Django 3.2.9 on 2021-12-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_auto_20211209_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber_policy',
            name='delivery_end_point',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
