# Generated by Django 3.2.9 on 2021-12-09 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0021_alter_subscriber_policy_delivery_end_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber_policy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
